[package]
name = "flight_booker"
edition = "2021"
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floem = { path = "../.." }
time = { version = "0.3.31", features = ["parsing", "macros"] }
