[package]
name              = "floem_reactive"
version.workspace = true
edition           = "2021"
repository        = "https://github.com/lapce/floem"
description       = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
smallvec = "1.10.0"
