//! # Floem Store
//!
//! Elm-style state management for Floem with structural field access.
//!
//! This crate provides an alternative to signals for managing complex, structured state.
//! Instead of nesting signals inside structs (which can cause lifetime issues when
//! child scopes are disposed), state lives in a central `Store` and is accessed via
//! `Binding` handles that can be derived for nested fields.
//!
//! ## Key Concepts
//!
//! - **Store**: Owns the state tree, not tied to any scope
//! - **Binding**: Handle pointing to a location in a Store (like a live lens with data)
//! - **Lens**: Stateless accessor recipe for navigating the data structure
//! - **Updates are messages**: `binding.set(v)` queues an update, doesn't mutate directly
//!
//! ## Example
//!
//! ```rust,ignore
//! use floem_store::Lenses;
//!
//! #[derive(Lenses, Default)]
//! struct AppState {
//!     count: i32,
//!     #[nested]
//!     user: User,
//! }
//!
//! #[derive(Lenses, Default)]
//! struct User {
//!     name: String,
//!     age: i32,
//! }
//!
//! // Create a typed store wrapper (generated by derive)
//! let store = AppStateStore::new(AppState::default());
//!
//! // Access fields via generated methods - these return Bindings
//! let count = store.count();
//! let name = store.user().name();
//!
//! // Read and write
//! name.set("Alice".into());
//! assert_eq!(name.get(), "Alice");
//!
//! // Update with closure
//! count.update(|c| *c += 1);
//! ```

mod binding;
mod dyn_binding;
pub mod lens;
mod local_state;
mod path;
mod store;
mod traits;

#[cfg(test)]
mod tests;

pub use binding::Binding;
pub use dyn_binding::DynBinding;
pub use lens::{ComposedLens, IdentityLens, IndexLens, KeyLens, Lens};
pub use local_state::LocalState;
pub use store::Store;

// Re-export derive macro
pub use floem_store_derive::Lenses;

// Re-export IndexMap for keyed collections with O(1) access
pub use indexmap::IndexMap;

// Re-export reactive traits for convenience
pub use floem_reactive::{SignalGet, SignalTrack, SignalUpdate, SignalWith};
