//! The [`Style`] map, its helpers, and expression-style counterpart.
//!
//! [`Style`] is the core hashmap of style keys to erased values that the
//! cascade consumes. It also carries the inherited-context map, the
//! deterministic merge id, and cached flags used for fast-path early-exits.
//!
//! [`ExprStyle`] is a thin wrapper that accepts [`ContextValue`]-typed setters
//! and merges into a [`Style`] when built. [`ContextRef<P>`] is the companion
//! zero-sized marker for reading a context prop.
//!
//! [`DeferredStyleEffect`] packages a closure that runs during
//! `resolve_nested_maps` to let host code observe resolved context values.
//!
//! [`BuiltinStyle`] is the `Style`-derived getter façade; its getter methods
//! are generated by `define_builtin_props!` in [`crate::builtin_props`].

use std::any::Any;
use std::collections::HashMap;
use std::fmt::{self, Debug};
use std::marker::PhantomData;
use std::rc::Rc;

use rustc_hash::FxHashMap;
use smallvec::SmallVec;

use crate::cascade::{
    fx_hash_map_with_capacity, responsive_selectors_key, structural_selectors_key, take_any,
    ResponsiveSelector, ResponsiveSelectorRules, ResponsiveSelectors, StructuralSelectorRules,
    StructuralSelectors,
};
use crate::context_value::ContextValue;
use crate::merge_id::{combine_merge_ids, next_style_merge_id, DEFERRED_EFFECTS_KEY};
use crate::props::{
    StyleClass, StyleClassRef, StyleDebugGroup, StyleKey, StyleKeyInfo, StyleProp, StylePropRef,
};
use crate::responsive::ScreenSize;
use crate::selectors::{NthChild, StructuralSelector, StyleSelector, StyleSelectors};
use crate::style_value::{StyleMapValue, StyleValue};
use crate::transition::Transition;
use crate::unit::Pt;

#[derive(Clone)]
pub struct DeferredStyleEffect {
    run: Rc<dyn Fn(&Style)>,
}

impl DeferredStyleEffect {
    #[doc(hidden)]
    pub fn new(run: impl Fn(&Style) + 'static) -> Self {
        Self { run: Rc::new(run) }
    }

    fn run(&self, style: &Style) {
        (self.run)(style);
    }
}

#[derive(Clone, Default, Debug)]
pub struct ExprStyle {
    pub(crate) style: Style,
}

impl From<Style> for ExprStyle {
    fn from(style: Style) -> Self {
        Self { style }
    }
}

impl From<ExprStyle> for Style {
    fn from(style: ExprStyle) -> Self {
        style.style
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ContextRef<P: StyleProp> {
    _marker: PhantomData<P>,
}

impl<P: StyleProp> ContextRef<P> {
    /// Create a deferred value from the current context prop.
    ///
    /// This is for producing another style value from context, such as
    /// `font_size(fs.def(|fs| fs * 0.85))` or `background(t.def(|t| t.bg_base()))`.
    ///
    /// You can read `def` either as "function definition" or as shorthand for
    /// "defer": it packages a closure that will be evaluated later when the
    /// resulting value is needed.
    ///
    /// The closure is evaluated only if the property using the returned [`ContextValue`]
    /// is actually read later. It does not run eagerly during `resolve_nested_maps`, so
    /// it should not be used for side effects that must always happen during style
    /// resolution. Use [`Style::defer`] for that.
    pub fn def<T>(self, f: impl Fn(P::Type) -> T + 'static) -> ContextValue<T>
    where
        P::Type: 'static,
        T: 'static,
    {
        ContextValue::new(move |style: &Style| {
            let value = style.get_prop::<P>().unwrap_or_else(P::default_value);
            f(value)
        })
    }

    pub fn map<T>(self, f: impl Fn(P::Type) -> T + 'static) -> ContextValue<T>
    where
        P::Type: 'static,
        T: 'static,
    {
        self.def(f)
    }

    pub(crate) fn into_deferred(self, f: impl Fn(P::Type) + 'static) -> DeferredStyleEffect
    where
        P::Type: 'static,
    {
        let effect = self.def(move |value| {
            f(value);
        });
        DeferredStyleEffect::new(move |style| {
            effect.resolve_erased(style as &dyn Any);
        })
    }
}

impl ExprStyle {
    pub fn new() -> Self {
        Self {
            style: Style::new(),
        }
    }

    pub fn build(self) -> Style {
        self.style
    }

    pub fn map(self, over: impl FnOnce(Self) -> Self) -> Self {
        over(self)
    }

    pub(crate) fn merge(mut self, over: Style) -> Self {
        self.style.apply_mut(&over);
        self
    }

    pub fn apply_if(self, cond: bool, f: impl FnOnce(Self) -> Self) -> Self {
        if cond { f(self) } else { self }
    }

    pub fn set<P: StyleProp>(mut self, prop: P, value: impl Into<StyleValue<P::Type>>) -> Self {
        self.style = self.style.set_style_value(prop, value.into());
        self
    }

    pub fn set_context<P: StyleProp>(mut self, prop: P, value: ContextValue<P::Type>) -> Self {
        self.style = self.style.set_context(prop, value);
        self
    }

    pub fn set_from_context<C: StyleProp, P: StyleProp>(
        mut self,
        prop: P,
        context: ContextRef<C>,
        f: impl Fn(C::Type) -> P::Type + 'static,
    ) -> Self
    where
        C::Type: 'static,
        P::Type: 'static,
    {
        self.style = self.style.set_from_context(prop, context, f);
        self
    }

    pub fn set_context_opt<P: StyleProp<Type = Option<T>>, T: 'static>(
        mut self,
        prop: P,
        value: ContextValue<Option<T>>,
    ) -> Self {
        self.style = self.style.set_context_opt(prop, value);
        self
    }

    pub fn set_from_context_opt<C: StyleProp, P: StyleProp<Type = Option<T>>, T: 'static>(
        mut self,
        prop: P,
        context: ContextRef<C>,
        f: impl Fn(C::Type) -> Option<T> + 'static,
    ) -> Self
    where
        C::Type: 'static,
    {
        self.style = self.style.set_from_context_opt(prop, context, f);
        self
    }

    pub fn with<P: StyleProp>(self, f: impl FnOnce(ExprStyle, ContextRef<P>) -> ExprStyle) -> Self {
        f(self, ContextRef::default())
    }

    pub fn hover(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().hover(|s| style(s.into()).into()))
    }

    pub fn focus(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().focus(|s| style(s.into()).into()))
    }

    pub fn focus_visible(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().focus_visible(|s| style(s.into()).into()))
    }

    pub fn focus_within(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().focus_within(|s| style(s.into()).into()))
    }

    pub fn active(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().active(|s| style(s.into()).into()))
    }

    pub fn disabled(self, style: impl FnOnce(ExprStyle) -> ExprStyle) -> Self {
        self.merge(Style::default().disabled(|s| style(s.into()).into()))
    }

    pub fn class<C: StyleClass>(
        self,
        class: C,
        style: impl FnOnce(ExprStyle) -> ExprStyle,
    ) -> Self {
        self.merge(Style::default().class(class, |s| style(s.into()).into()))
    }
}

#[derive(Clone)]
pub struct Style {
    #[doc(hidden)]
    pub map: Rc<FxHashMap<StyleKey, Rc<dyn Any>>>,
    #[doc(hidden)]
    pub inherited_context: Option<Rc<FxHashMap<StyleKey, Rc<dyn Any>>>>,
    /// Deterministic identity for style merges.
    merge_id: u64,
    /// Cached flag indicating whether this style contains any class maps.
    /// This enables O(1) early-exit in `apply_only_class_maps` for the common case
    /// where a view's style has no class definitions.
    has_class_maps: bool,
    /// Cached flag indicating whether this style contains any inherited properties.
    /// This enables O(1) early-exit in `apply_only_inherited` for the common case
    /// where a view's style has no inherited properties.
    has_inherited: bool,
    /// Cached bitmask of which selectors are present in this style (including nested).
    /// Updated incrementally when selectors are added via `apply_iter`, `set_selector`, etc.
    /// Enables O(1) checks in `resolve_selectors` to skip absent selectors.
    pub(crate) cached_selectors: StyleSelectors,
    /// Cached flag indicating whether this style contains any context-dependent values.
    /// Styles with context values cannot be reliably cached because their content_hash()
    /// is constant (all context values hash to 1), so different context values produce
    /// the same cache key despite resolving to different output.
    has_context_values: bool,
}

impl Default for Style {
    fn default() -> Self {
        Self::with_capacity(0)
    }
}

impl Style {
    #[doc(hidden)]
    pub fn with_capacity(capacity: usize) -> Self {
        let map = Rc::new(fx_hash_map_with_capacity(capacity));
        Self {
            merge_id: next_style_merge_id(),
            map,
            inherited_context: None,
            has_class_maps: false,
            has_inherited: false,
            cached_selectors: StyleSelectors::empty(),
            has_context_values: false,
        }
    }

    #[doc(hidden)]
    pub fn map_mut(&mut self) -> &mut FxHashMap<StyleKey, Rc<dyn Any>> {
        Rc::make_mut(&mut self.map)
    }

    pub fn new() -> Self {
        Self::with_capacity(0)
    }

    #[doc(hidden)]
    pub fn with_inherited_context(mut self, inherited: &Style) -> Self {
        self.inherited_context = Some(inherited.map.clone());
        self
    }

    /// Apply only inherited properties from `from` style to `to` style.
    /// This is used during style propagation to pass inherited values to children.
    ///
    /// Only properties marked as `inherited: true` in their `StylePropInfo` are applied.
    /// This is more efficient than `apply_mut` when we only need to propagate
    /// inherited properties like font-size, color, etc.
    pub fn apply_only_inherited(to: &mut Style, from: &Style) {
        if from.any_inherited() {
            for (k, v) in from.map.iter().filter(|(p, _)| p.inherited()) {
                let StyleKeyInfo::Prop(info) = k.info else {
                    continue;
                };
                to.map_mut()
                    .insert(*k, (info.resolve_inherited_any)(&**v, from as &dyn std::any::Any));
                to.has_inherited = true;
            }
            to.merge_id = combine_merge_ids(to.merge_id, from.merge_id);
        }
    }

    /// Apply inherited properties and class nested maps from `from` style to `to` style.
    ///
    /// This is used during style propagation to pass both inherited values and
    /// class definitions to children. Class nested maps (like `.class(ListItemClass, ...)`)
    /// need to flow to descendants so they can apply the styling when they have matching classes.
    pub fn apply_inherited_and_class_maps(to: &mut Rc<Style>, from: &Style) {
        let has_inherited = from.any_inherited();
        // O(1) check using cached flag
        let has_class_maps = from.has_class_maps;

        if has_inherited || has_class_maps {
            let mut new_style = (**to).clone();

            // Apply inherited properties
            if has_inherited {
                for (k, v) in from.map.iter().filter(|(p, _)| p.inherited()) {
                    let StyleKeyInfo::Prop(info) = k.info else {
                        continue;
                    };
                    new_style.map_mut().insert(
                        *k,
                        (info.resolve_inherited_any)(&**v, from as &dyn std::any::Any),
                    );
                    new_style.has_inherited = true;
                }
                new_style.merge_id = combine_merge_ids(new_style.merge_id, from.merge_id);
            }

            // Apply class nested maps so they flow to descendants
            if has_class_maps {
                let class_maps = from
                    .map
                    .iter()
                    .filter(|(k, _)| matches!(k.info, StyleKeyInfo::Class(..)));
                new_style.apply_iter(class_maps);
                new_style.merge_id = combine_merge_ids(new_style.merge_id, from.merge_id);
            }

            *to = Rc::new(new_style);
        }
    }

    /// Apply only class nested maps from `from` style to `to` style.
    /// This is used during style propagation to pass class definitions to children.
    ///
    /// Only class nested maps (`.class(SomeClass, ...)`) are applied, not inherited props.
    pub fn apply_only_class_maps(to: &mut Style, from: &Style) {
        if !from.has_class_maps {
            return;
        }
        let class_maps = from
            .map
            .iter()
            .filter(|(k, _)| matches!(k.info, StyleKeyInfo::Class(..)));
        to.apply_iter(class_maps);
        to.merge_id = combine_merge_ids(to.merge_id, from.merge_id);
    }

    #[doc(hidden)]
    pub fn merge_id(&self) -> u64 {
        self.merge_id
    }

    /// Returns the raw pointer of the inner `Rc<FxHashMap>` as a `usize`.
    /// Used by the style cache for O(1) identity comparison.
    #[doc(hidden)]
    pub fn map_ptr(&self) -> usize {
        Rc::as_ptr(&self.map) as usize
    }

    /// Whether this style contains any context-dependent values.
    #[doc(hidden)]
    pub fn has_context_values(&self) -> bool {
        self.has_context_values
    }

    /// Whether this style contains structural selectors (`:first-child`, `:nth-child`, etc.).
    /// Styles with structural selectors depend on `child_index`/`sibling_count` which are
    /// per-position values not captured in the cache key, so they must be excluded from caching.
    #[doc(hidden)]
    pub fn has_structural_selectors(&self) -> bool {
        self.map.contains_key(&structural_selectors_key())
    }

    pub fn class_maps_eq(&self, other: &Style) -> SmallVec<[StyleClassRef; 4]> {
        // Pass 1: every Class entry in self must exist in other
        let mut changed = SmallVec::new();
        for (k, v) in self.map.iter() {
            let StyleKeyInfo::Class(_) = k.info else {
                continue;
            };

            match other.map.get(k) {
                Some(other_v) => {
                    let v_style = v.downcast_ref::<Style>().unwrap();
                    let other_v_style = other_v.downcast_ref::<Style>().unwrap();

                    if v_style.merge_id != other_v_style.merge_id {
                        changed.push(StyleClassRef { key: *k });
                    }
                }
                None => {
                    changed.push(StyleClassRef { key: *k });
                }
            }
        }

        // Pass 2: ensure other does not contain extra Class entries
        for k in other.map.keys() {
            if !matches!(k.info, StyleKeyInfo::Class(..)) {
                continue;
            }

            if !self.map.contains_key(k) {
                changed.push(StyleClassRef { key: *k });
            }
        }

        changed
    }

    #[doc(hidden)]
    pub fn get_transition<P: StyleProp>(&self) -> Option<Transition> {
        self.map
            .get(&P::prop_ref().info().transition_key)
            .map(|v| v.downcast_ref::<Transition>().unwrap().clone())
    }

    fn get_prop_from_map<P: StyleProp>(
        map: &FxHashMap<StyleKey, Rc<dyn Any>>,
        context_style: &Style,
    ) -> Option<P::Type> {
        map.get(&P::key()).and_then(
            |v| match v.downcast_ref::<StyleMapValue<P::Type>>().unwrap() {
                StyleMapValue::Animated(v) | StyleMapValue::Val(v) => Some(v.clone()),
                StyleMapValue::Context(context_value) => {
                    Some(context_style.resolve_context(context_value))
                }
                StyleMapValue::Unset => None,
            },
        )
    }

    fn get_style_value_from_map<P: StyleProp>(
        map: &FxHashMap<StyleKey, Rc<dyn Any>>,
        context_style: &Style,
    ) -> Option<StyleValue<P::Type>> {
        map.get(&P::key()).map(
            |v| match v.downcast_ref::<StyleMapValue<P::Type>>().unwrap() {
                StyleMapValue::Val(v) => StyleValue::Val(v.clone()),
                StyleMapValue::Animated(v) => StyleValue::Animated(v.clone()),
                StyleMapValue::Context(v) => {
                    StyleValue::Val(context_style.resolve_context(v))
                }
                StyleMapValue::Unset => StyleValue::Unset,
            },
        )
    }

    #[doc(hidden)]
    pub fn get_prop_or_default<P: StyleProp>(&self) -> P::Type {
        self.get_prop::<P>().unwrap_or_else(|| P::default_value())
    }

    #[doc(hidden)]
    pub fn get_prop<P: StyleProp>(&self) -> Option<P::Type> {
        Self::get_prop_from_map::<P>(&self.map, self).or_else(|| {
            self.inherited_context
                .as_ref()
                .and_then(|map| Self::get_prop_from_map::<P>(map, self))
        })
    }

    #[doc(hidden)]
    pub fn get_prop_style_value<P: StyleProp>(&self) -> StyleValue<P::Type> {
        Self::get_style_value_from_map::<P>(&self.map, self)
            .or_else(|| {
                self.inherited_context
                    .as_ref()
                    .and_then(|map| Self::get_style_value_from_map::<P>(map, self))
            })
            .unwrap_or(StyleValue::Base)
    }

    #[doc(hidden)]
    pub fn style_props(&self) -> impl Iterator<Item = StylePropRef> + '_ {
        self.map.keys().filter_map(|p| match p.info {
            StyleKeyInfo::Prop(..) => Some(StylePropRef { key: *p }),
            _ => None,
        })
    }

    #[doc(hidden)]
    pub fn selectors(&self) -> StyleSelectors {
        self.cached_selectors
    }

    /// Recompute selectors by traversing the map. Used for debug assertions.
    #[cfg(debug_assertions)]
    #[doc(hidden)]
    pub fn compute_selectors_slow(&self) -> StyleSelectors {
        let mut result = StyleSelectors::empty();

        for (k, v) in self.map.iter() {
            match k.info {
                StyleKeyInfo::Selector(selector) => {
                    result = result
                        .union(*selector)
                        .union(v.downcast_ref::<Style>().unwrap().selectors());
                }
                StyleKeyInfo::StructuralSelectors => {
                    let rules = &v.downcast_ref::<StructuralSelectors>().unwrap().0;
                    for (_, nested_style) in rules {
                        result = result.union(nested_style.as_ref().selectors());
                    }
                }
                StyleKeyInfo::ResponsiveSelectors => {
                    result = result.responsive();
                    let rules = &v.downcast_ref::<ResponsiveSelectors>().unwrap().0;
                    for (_, nested_style) in rules {
                        result = result.union(nested_style.as_ref().selectors());
                    }
                }
                StyleKeyInfo::DebugGroup(..) => {}
                _ => {}
            }
        }

        result
    }

    pub fn apply_class<C: StyleClass>(mut self, _class: C) -> Style {
        if let Some(map) = self.map.get(&C::key()).cloned() {
            self.apply_mut(map.downcast_ref::<Style>().unwrap());
        }
        self
    }

    pub fn apply_selectors(mut self, selectors: &[StyleSelector]) -> Style {
        use crate::selectors::StyleSelectorKey;
        for selector in selectors {
            if let Some(map) = self.get_nested_map(selector.to_key()) {
                let resolved = map.apply_selectors(selectors);
                self.apply_mut(&resolved);
            }
        }
        if self.get(crate::builtin_props::Selected)
            && let Some(map) = self.get_nested_map(StyleSelector::Selected.to_key())
        {
            let resolved = map.apply_selectors(&[StyleSelector::Selected]);
            self.apply_mut(&resolved);
        }
        self
    }

    /// Build style values from a context prop without introducing a deferred style map pass.
    ///
    /// The closure runs immediately and must produce an ordinary style map. Any deferred
    /// context work is captured at the individual property-value level through
    /// [`ContextRef::map`].
    pub fn with<P: StyleProp>(self, f: impl FnOnce(ExprStyle, ContextRef<P>) -> ExprStyle) -> Self {
        f(ExprStyle { style: self }, ContextRef::default()).style
    }

    #[doc(hidden)]
    pub fn get_nested_map(&self, key: StyleKey) -> Option<Style> {
        self.map
            .get(&key)
            .map(|map| map.downcast_ref::<Style>().unwrap().clone())
    }

    #[doc(hidden)]
    pub fn debug_group_enabled(&self, key: StyleKey) -> bool {
        self.map
            .get(&key)
            .and_then(|value| value.downcast_ref::<bool>().copied())
            .unwrap_or(false)
    }

    #[doc(hidden)]
    pub fn remove_nested_map(&mut self, key: StyleKey) -> Option<Style> {
        let removed = self.map_mut().remove(&key).map(take_any::<Style>);
        if removed.is_some() {
            self.merge_id = next_style_merge_id();
        }
        removed
    }

    /// Check if this style has any inherited properties.
    /// Used to determine if children should be re-styled when this view's style changes.
    /// O(1) using cached flag.
    #[doc(hidden)]
    pub fn any_inherited(&self) -> bool {
        self.has_inherited
    }

    #[doc(hidden)]
    pub fn inherited(&self) -> Style {
        let mut new = Style::new();
        if self.any_inherited() {
            let inherited = self.map.iter().filter(|(p, _)| p.inherited());

            new.apply_iter(inherited);
            new.merge_id = combine_merge_ids(new.merge_id, self.merge_id);
        }
        new
    }

    fn set_selector(&mut self, selector: StyleSelector, map: Style) {
        use crate::selectors::StyleSelectorKey;
        self.set_map_selector(selector.to_key(), map)
    }

    fn set_structural_selector(&mut self, selector: StructuralSelector, map: Style) {
        self.cached_selectors |= map.cached_selectors;
        let key = structural_selectors_key();
        let mut rules = self
            .map_mut()
            .remove(&key)
            .map(|current| take_any::<StructuralSelectors>(current).0)
            .unwrap_or_default();
        rules.push((selector, Rc::new(map)));
        self.map_mut()
            .insert(key, Rc::new(StructuralSelectors(rules)));
        self.merge_id = next_style_merge_id();
    }

    fn set_responsive_selector(&mut self, selector: ResponsiveSelector, map: Style) {
        self.cached_selectors |= StyleSelectors::RESPONSIVE;
        self.cached_selectors |= map.cached_selectors;
        let key = responsive_selectors_key();
        let mut rules = self
            .map_mut()
            .remove(&key)
            .map(|current| take_any::<ResponsiveSelectors>(current).0)
            .unwrap_or_default();
        rules.push((selector, Rc::new(map)));
        self.map_mut()
            .insert(key, Rc::new(ResponsiveSelectors(rules)));
        self.merge_id = next_style_merge_id();
    }

    fn set_map_selector(&mut self, key: StyleKey, map: Style) {
        // Track selector presence
        if let StyleKeyInfo::Selector(sel) = key.info {
            self.cached_selectors |= *sel;
            self.cached_selectors |= map.cached_selectors;
        }
        let value = if let Some(current) = self.map_mut().remove(&key) {
            let mut current: Style = take_any(current);
            current.apply_mut(&map);
            Rc::new(current)
        } else {
            Rc::new(map)
        };
        self.map_mut().insert(key, value);
        self.merge_id = next_style_merge_id();
    }

    fn set_class(&mut self, class: StyleClassRef, map: Style) {
        self.has_class_maps = true;
        self.set_map_selector(class.key, map)
    }

    pub fn debug_group<G: StyleDebugGroup>(mut self, _group: G) -> Self {
        self.map_mut().insert(G::key(), Rc::new(true));
        self.merge_id = next_style_merge_id();
        self
    }

    pub fn unset_debug_group<G: StyleDebugGroup>(mut self, _group: G) -> Self {
        self.map_mut().insert(G::key(), Rc::new(false));
        self.merge_id = next_style_merge_id();
        self
    }

    pub fn builtin(&self) -> BuiltinStyle<'_> {
        BuiltinStyle { style: self }
    }

    #[doc(hidden)]
    pub fn apply_iter<'a>(
        &mut self,
        iter: impl Iterator<Item = (&'a StyleKey, &'a Rc<dyn Any>)>,
    ) {
        for (k, v) in iter {
            match k.info {
                StyleKeyInfo::Class(..) | StyleKeyInfo::Selector(..) => {
                    // Track class maps for O(1) early-exit in apply_only_class_maps
                    if matches!(k.info, StyleKeyInfo::Class(..)) {
                        self.has_class_maps = true;
                    }
                    // Track selectors for O(1) selector presence checks
                    if let StyleKeyInfo::Selector(sel) = k.info {
                        self.cached_selectors |= *sel;
                        if let Some(nested) = v.downcast_ref::<Style>() {
                            self.cached_selectors |= nested.cached_selectors;
                        }
                    }
                    if let Some(existing_rc) = self.map_mut().remove(k) {
                        if Rc::ptr_eq(&existing_rc, v) {
                            self.map_mut().insert(*k, existing_rc);
                            continue;
                        }

                        let mut current: Style = take_any(existing_rc);
                        current.apply_mut(v.downcast_ref::<Style>().unwrap());
                        self.map_mut().insert(*k, Rc::new(current));
                    } else {
                        self.map_mut().insert(*k, v.clone());
                    }
                }
                StyleKeyInfo::StructuralSelectors => {
                    // Propagate nested selectors from structural rules
                    let rules = &v.downcast_ref::<StructuralSelectors>().unwrap().0;
                    for (_, nested) in rules {
                        self.cached_selectors |= nested.cached_selectors;
                    }
                    let merged = if let Some(current) = self.map_mut().remove(k) {
                        let new_rules = &v.downcast_ref::<StructuralSelectors>().unwrap().0;
                        let current: StructuralSelectors = take_any(current);
                        let mut merged: StructuralSelectorRules = current.0;
                        merged.extend(new_rules.iter().cloned());
                        Rc::new(StructuralSelectors(merged))
                    } else {
                        v.clone()
                    };
                    self.map_mut().insert(*k, merged);
                }
                StyleKeyInfo::ResponsiveSelectors => {
                    self.cached_selectors |= StyleSelectors::RESPONSIVE;
                    // Propagate nested selectors from responsive rules
                    let rules = &v.downcast_ref::<ResponsiveSelectors>().unwrap().0;
                    for (_, nested) in rules {
                        self.cached_selectors |= nested.cached_selectors;
                    }
                    let merged = if let Some(current) = self.map_mut().remove(k) {
                        let new_rules = &v.downcast_ref::<ResponsiveSelectors>().unwrap().0;
                        let current: ResponsiveSelectors = take_any(current);
                        let mut merged: ResponsiveSelectorRules = current.0;
                        merged.extend(new_rules.iter().cloned());
                        Rc::new(ResponsiveSelectors(merged))
                    } else {
                        v.clone()
                    };
                    self.map_mut().insert(*k, merged);
                }
                StyleKeyInfo::DeferredEffects => {
                    let merged = if let Some(current) = self.map_mut().remove(k) {
                        let mut current: Vec<DeferredStyleEffect> = take_any(current);
                        current.extend(
                            v.downcast_ref::<Vec<DeferredStyleEffect>>()
                                .unwrap()
                                .iter()
                                .cloned(),
                        );
                        Rc::new(current)
                    } else {
                        v.clone()
                    };
                    self.map_mut().insert(*k, merged);
                }
                StyleKeyInfo::Transition | StyleKeyInfo::DebugGroup(..) => {
                    self.map_mut().insert(*k, v.clone());
                }
                StyleKeyInfo::Prop(info) => {
                    // Track inherited props for O(1) early-exit in apply_only_inherited
                    if info.inherited {
                        self.has_inherited = true;
                    }
                    self.map_mut().insert(*k, v.clone());
                }
            }
        }
    }

    #[doc(hidden)]
    pub fn apply_mut(&mut self, over: &Style) {
        // FAST PATH: identical semantic payload identity
        if self.merge_id == over.merge_id {
            return;
        }
        let over_merge_id = over.merge_id;
        self.apply_iter(over.map.iter());
        self.has_context_values |= over.has_context_values;
        self.merge_id = combine_merge_ids(self.merge_id, over_merge_id);
    }

    /// Resolve a [`ContextValue`] against this style.
    ///
    /// The closure receives this style type-erased and returns the resolved
    /// value. Closures are expected to be pure functions of the cascaded
    /// style they receive — if a closure reads external signals, the host
    /// is responsible for wrapping the closure in its own reactive-scope
    /// machinery before handing it to [`ContextValue::new`].
    ///
    /// `pub` because `prop!` expansions in downstream crates call it from
    /// their generated code.
    #[doc(hidden)]
    pub fn resolve_context<T: 'static>(&self, cv: &ContextValue<T>) -> T {
        cv.resolve_erased(self as &dyn Any)
    }

    /// Apply another `Style` to this style, returning a new `Style` with the overrides
    ///
    /// `StyleValue::Val` will override the value with the given value
    /// `StyleValue::Unset` will unset the value, causing it to fall back to the default.
    /// `StyleValue::Base` will leave the value as-is, whether falling back to the default
    /// or using the value in the `Style`.
    pub fn apply(mut self, over: Style) -> Style {
        self.apply_mut(&over);
        self
    }

    pub fn map(self, over: impl FnOnce(Self) -> Self) -> Self {
        over(self)
    }

    /// Apply multiple `Style`s to this style, returning a new `Style` with the overrides.
    /// Later styles take precedence over earlier styles.
    pub fn apply_overriding_styles(self, overrides: impl Iterator<Item = Style>) -> Style {
        overrides.fold(self, |acc, x| acc.apply(x))
    }
}

impl Debug for Style {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Style")
            .field(
                "map",
                &self
                    .map
                    .iter()
                    .map(|(p, v)| (*p, (p.debug_any(&**v))))
                    .collect::<HashMap<StyleKey, String>>(),
            )
            .finish()
    }
}

// ============================================================================
// Deferred effects, selector setters, and the main action API on Style
// ============================================================================

impl Style {
    fn deferred_effects(&self) -> impl Iterator<Item = &DeferredStyleEffect> {
        self.map
            .get(&DEFERRED_EFFECTS_KEY)
            .into_iter()
            .flat_map(|effects| {
                effects
                    .downcast_ref::<Vec<DeferredStyleEffect>>()
                    .into_iter()
                    .flat_map(|effects| effects.iter())
            })
    }

    pub(crate) fn run_deferred_effects(&self) {
        for effect in self.deferred_effects() {
            effect.run(self);
        }
    }

    fn push_deferred_effect(mut self, effect: DeferredStyleEffect) -> Self {
        let mut effects = self
            .map
            .get(&DEFERRED_EFFECTS_KEY)
            .and_then(|effects| effects.downcast_ref::<Vec<DeferredStyleEffect>>())
            .cloned()
            .unwrap_or_default();
        effects.push(effect);
        self.map_mut()
            .insert(DEFERRED_EFFECTS_KEY, Rc::new(effects));
        self.merge_id = next_style_merge_id();
        self
    }

    /// Gets the value of a style property, returning the default if not set.
    pub fn get<P: StyleProp>(&self, _prop: P) -> P::Type {
        self.get_prop_or_default::<P>()
    }

    /// Gets the raw style value of a property, including unset and base states.
    pub fn get_style_value<P: StyleProp>(&self, _prop: P) -> StyleValue<P::Type> {
        self.get_prop_style_value::<P>()
    }

    /// Sets a style property to a specific value.
    pub fn set<P: StyleProp>(self, prop: P, value: impl Into<P::Type>) -> Self {
        self.set_style_value(prop, StyleValue::Val(value.into()))
    }

    /// Sets a property to a deferred context-derived value.
    pub fn set_context<P: StyleProp>(self, prop: P, value: ContextValue<P::Type>) -> Self {
        self.set_style_value(prop, StyleValue::Context(value))
    }

    /// Register a deferred side effect for a context prop.
    ///
    /// Unlike [`ContextRef::def`], this does not produce a property value. The closure is
    /// guaranteed to run during nested-style resolution after inherited context has been
    /// attached, even if no property later reads the context value.
    ///
    /// Use this for debug-view setup and similar side effects:
    /// `Style::new().defer::<Theme>(|t| color.set(t.primary()))`.
    pub fn defer<P: StyleProp>(self, f: impl Fn(P::Type) + 'static) -> Self
    where
        P::Type: 'static,
    {
        self.push_deferred_effect(ContextRef::<P>::default().into_deferred(f))
    }

    pub fn set_from_context<C: StyleProp, P: StyleProp>(
        self,
        prop: P,
        context: ContextRef<C>,
        f: impl Fn(C::Type) -> P::Type + 'static,
    ) -> Self
    where
        C::Type: 'static,
        P::Type: 'static,
    {
        self.set_context(prop, context.def(f))
    }

    /// Sets a property to a deferred optional context-derived value.
    ///
    /// `None` resolves to an unset property, allowing the base/fallback style to win.
    pub fn set_context_opt<P: StyleProp<Type = Option<T>>, T: 'static>(
        self,
        prop: P,
        value: ContextValue<Option<T>>,
    ) -> Self {
        self.set_style_value(prop, StyleValue::Context(value))
    }

    pub fn set_from_context_opt<C: StyleProp, P: StyleProp<Type = Option<T>>, T: 'static>(
        self,
        prop: P,
        context: ContextRef<C>,
        f: impl Fn(C::Type) -> Option<T> + 'static,
    ) -> Self
    where
        C::Type: 'static,
    {
        self.set_context_opt(prop, context.def(f))
    }

    pub fn set_style_value<P: StyleProp>(mut self, _prop: P, value: StyleValue<P::Type>) -> Self {
        let previous_value = self.map.get(&P::key()).cloned();
        let insert = match value {
            StyleValue::Val(value) => StyleMapValue::Val(value),
            StyleValue::Animated(value) => StyleMapValue::Animated(value),
            StyleValue::Context(value) => {
                self.has_context_values = true;
                let previous_value = previous_value.clone();
                StyleMapValue::Context(ContextValue::new(move |style: &Style| {
                    let mut base_style = style.clone();
                    base_style.map_mut().remove(&P::key());
                    // A deferred value for property `P` is allowed to read `P` from context,
                    // e.g. `FontSize := FontSize * 0.8`. If we resolved against the current
                    // style as-is, that lookup would see the context expression we are
                    // installing right now and recurse forever.
                    //
                    // Instead, same-prop context reads resolve against the previous effective
                    // value for `P`: the previous local value if there was one, otherwise the
                    // inherited fallback carried by `Style`.
                    if let Some(previous_value) = previous_value.clone() {
                        let previous_value = match previous_value
                            .downcast_ref::<StyleMapValue<P::Type>>()
                            .unwrap()
                        {
                            StyleMapValue::Val(value) | StyleMapValue::Animated(value) => {
                                Some(value.clone())
                            }
                            StyleMapValue::Context(context_value) => {
                                Some(base_style.resolve_context(context_value))
                            }
                            StyleMapValue::Unset => None,
                        };

                        if let Some(previous_value) = previous_value {
                            base_style
                                .map_mut()
                                .insert(P::key(), Rc::new(StyleMapValue::Val(previous_value)));
                        }
                    }
                    base_style.resolve_context(&value)
                }))
            }
            StyleValue::Unset => StyleMapValue::Unset,
            StyleValue::Base => {
                if self.map_mut().remove(&P::key()).is_some() {
                    self.merge_id = next_style_merge_id();
                }
                return self;
            }
        };
        // Track inherited props for O(1) early-exit in apply_only_inherited
        if P::prop_ref().info().inherited {
            self.has_inherited = true;
        }
        self.map_mut().insert(P::key(), Rc::new(insert));
        self.merge_id = next_style_merge_id();
        self
    }

    /// Sets a transition animation for a specific style property.
    pub fn transition<P: StyleProp>(mut self, _prop: P, transition: Transition) -> Self {
        self.map_mut()
            .insert(P::prop_ref().info().transition_key, Rc::new(transition));
        self.merge_id = next_style_merge_id();
        self
    }

    #[doc(hidden)]
    pub fn selector(mut self, selector: StyleSelector, style: impl FnOnce(Style) -> Style) -> Self {
        let over = style(Style::default());
        self.set_selector(selector, over);
        self
    }

    #[doc(hidden)]
    pub fn structural_selector(
        mut self,
        selector: StructuralSelector,
        style: impl FnOnce(Style) -> Style,
    ) -> Self {
        let over = style(Style::default());
        self.set_structural_selector(selector, over);
        self
    }

    /// The visual style to apply when the mouse hovers over the view
    pub fn hover(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Hover, style)
    }

    /// The visual style to apply when the view has keyboard focus.
    pub fn focus(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Focus, style)
    }

    /// Similar to the `:focus-visible` css selector, this style only activates when the view was focused via tab or arrow navigation.
    pub fn focus_visible(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::FocusVisible, style)
    }

    /// Similar to the `:focus-within` css selector, this style activates when this
    /// view or any descendant is in the focus path.
    pub fn focus_within(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::FocusWithin, style)
    }

    /// Similar to the `:first-child` css selector.
    pub fn first_child(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.structural_selector(StructuralSelector::FirstChild, style)
    }

    /// Similar to the `:last-child` css selector.
    pub fn last_child(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.structural_selector(StructuralSelector::LastChild, style)
    }

    /// Similar to the `:nth-child(...)` css selector.
    pub fn nth_child(self, nth: NthChild, style: impl FnOnce(Style) -> Style) -> Self {
        self.structural_selector(StructuralSelector::NthChild(nth), style)
    }

    /// Convenience for `:nth-child(odd)`.
    pub fn odd(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.nth_child(NthChild::odd(), style)
    }

    /// Convenience for `:nth-child(even)`.
    pub fn even(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.nth_child(NthChild::even(), style)
    }

    /// The visual style to apply when the view is in a selected state.
    pub fn selected(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Selected, style)
    }

    /// The visual style to apply when the view is being dragged
    pub fn drag(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Dragging, style)
    }

    /// The visual style to apply when the view is disabled.
    pub fn disabled(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Disabled, style)
    }

    /// The visual style to apply when the application is in dark mode.
    pub fn dark_mode(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::DarkMode, style)
    }

    /// The visual style to apply when a file is being dragged over the view.
    pub fn file_hover(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::FileHover, style)
    }

    /// The visual style to apply when the view is being actively pressed.
    pub fn active(self, style: impl FnOnce(Style) -> Style) -> Self {
        self.selector(StyleSelector::Active, style)
    }

    /// Applies styles that activate at specific screen sizes (responsive design).
    pub fn responsive(mut self, size: ScreenSize, style: impl FnOnce(Style) -> Style) -> Self {
        let over = style(Style::default());
        self.set_responsive_selector(ResponsiveSelector::ScreenSize(size), over);
        self
    }

    /// Applies styles when window width is at least `min`.
    pub fn min_window_width(
        mut self,
        min: impl Into<Pt>,
        style: impl FnOnce(Style) -> Style,
    ) -> Self {
        let over = style(Style::default());
        self.set_responsive_selector(ResponsiveSelector::MinWidth(min.into()), over);
        self
    }

    /// Applies styles when window width is at most `max`.
    pub fn max_window_width(
        mut self,
        max: impl Into<Pt>,
        style: impl FnOnce(Style) -> Style,
    ) -> Self {
        let over = style(Style::default());
        self.set_responsive_selector(ResponsiveSelector::MaxWidth(max.into()), over);
        self
    }

    /// Applies styles when window width is within `[min, max]` (inclusive).
    pub fn window_width_range(
        mut self,
        min: impl Into<Pt>,
        max: impl Into<Pt>,
        style: impl FnOnce(Style) -> Style,
    ) -> Self {
        let over = style(Style::default());
        self.set_responsive_selector(
            ResponsiveSelector::WidthRange {
                min: min.into(),
                max: max.into(),
            },
            over,
        );
        self
    }

    /// Applies styles to views with a specific CSS class.
    pub fn class<C: StyleClass>(mut self, _class: C, style: impl FnOnce(Style) -> Style) -> Self {
        let over = style(Style::default());
        self.set_class(C::class_ref(), over);
        self
    }

    /// Allow the application of a function if the option exists.
    /// This is useful for chaining together a bunch of optional style changes.
    pub fn apply_opt<T>(self, opt: Option<T>, f: impl FnOnce(Self, T) -> Self) -> Self {
        if let Some(t) = opt { f(self, t) } else { self }
    }

    /// Allow the application of a function if the condition holds.
    /// This is useful for chaining together optional style changes.
    pub fn apply_if(self, cond: bool, f: impl FnOnce(Self) -> Self) -> Self {
        if cond { f(self) } else { self }
    }
}

pub struct BuiltinStyle<'a> {
    pub(crate) style: &'a Style,
}

impl Style {
    /// Build a [`FontSizeCx`](crate::unit::FontSizeCx) from the style's
    /// font-size and line-height props.
    pub fn font_size_cx(&self) -> crate::unit::FontSizeCx {
        let builtin = self.builtin();
        let font_size = builtin.font_size();
        let line_height = builtin.line_height();
        let line_height = line_height.resolve(font_size as f32);
        crate::unit::FontSizeCx::new(font_size, line_height as f64)
    }

    /// Convert to a [`taffy::style::Style`] used for layout computation.
    pub fn to_taffy_style(&self) -> taffy::style::Style {
        use taffy::prelude::{Rect, Size};
        use taffy::style::LengthPercentage;

        let style = self.builtin();
        let font_size_cx = self.font_size_cx();
        taffy::style::Style {
            display: style.display(),
            overflow: taffy::Point {
                x: self.get(crate::builtin_props::OverflowX),
                y: self.get(crate::builtin_props::OverflowY),
            },
            position: style.position(),
            size: Size {
                width: style.width().to_taffy_dim(&font_size_cx),
                height: style.height().to_taffy_dim(&font_size_cx),
            },
            min_size: Size {
                width: style.min_width().to_taffy_dim(&font_size_cx),
                height: style.min_height().to_taffy_dim(&font_size_cx),
            },
            max_size: Size {
                width: style.max_width().to_taffy_dim(&font_size_cx),
                height: style.max_height().to_taffy_dim(&font_size_cx),
            },
            flex_direction: style.flex_direction(),
            flex_grow: style.flex_grow(),
            flex_shrink: style.flex_shrink(),
            flex_basis: style.flex_basis().to_taffy_dim(&font_size_cx),
            flex_wrap: style.flex_wrap(),
            justify_content: style.justify_content(),
            justify_self: style.justify_self(),
            justify_items: style.justify_items(),
            align_items: style.align_items(),
            align_content: style.align_content(),
            align_self: style.align_self(),
            aspect_ratio: style.aspect_ratio(),
            border: Rect {
                left: LengthPercentage::length(style.border_left().width as f32),
                top: LengthPercentage::length(style.border_top().width as f32),
                right: LengthPercentage::length(style.border_right().width as f32),
                bottom: LengthPercentage::length(style.border_bottom().width as f32),
            },
            padding: Rect {
                left: style.padding_left().to_taffy(&font_size_cx),
                top: style.padding_top().to_taffy(&font_size_cx),
                right: style.padding_right().to_taffy(&font_size_cx),
                bottom: style.padding_bottom().to_taffy(&font_size_cx),
            },
            margin: Rect {
                left: style.margin_left().to_taffy_len_perc_auto(&font_size_cx),
                top: style.margin_top().to_taffy_len_perc_auto(&font_size_cx),
                right: style.margin_right().to_taffy_len_perc_auto(&font_size_cx),
                bottom: style.margin_bottom().to_taffy_len_perc_auto(&font_size_cx),
            },
            inset: Rect {
                left: style.inset_left().to_taffy_len_perc_auto(&font_size_cx),
                top: style.inset_top().to_taffy_len_perc_auto(&font_size_cx),
                right: style.inset_right().to_taffy_len_perc_auto(&font_size_cx),
                bottom: style.inset_bottom().to_taffy_len_perc_auto(&font_size_cx),
            },
            gap: Size {
                width: style.col_gap().to_taffy(&font_size_cx),
                height: style.row_gap().to_taffy(&font_size_cx),
            },
            grid_template_rows: style.grid_template_rows(),
            grid_template_columns: style.grid_template_columns(),
            grid_row: style.grid_row(),
            grid_column: style.grid_column(),
            grid_auto_rows: style.grid_auto_rows(),
            grid_auto_columns: style.grid_auto_columns(),
            grid_auto_flow: style.grid_auto_flow(),
            scrollbar_width: style.scrollbar_width().0 as f32,
            ..Default::default()
        }
    }
}

#[cfg(test)]
mod tests {
    //! Standalone Style tests covering `apply`, aggregate-setter round-trips,
    //! and context-value resolution at property-read time.

    use super::*;
    use crate::builtin_props::{Background, PaddingBottom, PaddingLeft, PaddingRight, TextColor};
    use crate::components::Padding;
    use crate::unit::Length;
    use peniko::color::palette::css;
    use peniko::Brush;

    #[test]
    fn apply_overrides_matching_props_and_preserves_others() {
        let style1 = Style::new().padding_left(32.0);
        let style2 = Style::new().padding_left(64.0);
        let style = style1.apply(style2);
        assert_eq!(style.get(PaddingLeft), Length::Pt(64.0));

        let style1 = Style::new().padding_left(32.0).padding_bottom(45.0);
        let style2 = Style::new().padding_left(64.0);
        let style = style1.apply(style2);
        assert_eq!(style.get(PaddingLeft), Length::Pt(64.0));
        assert_eq!(style.get(PaddingBottom), Length::Pt(45.0));
    }

    #[test]
    fn apply_padding_aggregate_matches_individual_setters() {
        let style1 = Style::new().apply_padding(Padding::new().left(32.0).bottom(45.0));
        let style2 = Style::new().apply_padding(Padding::new().left(64.0));
        let style = style1.apply(style2);
        assert_eq!(style.get(PaddingLeft), Length::Pt(64.0));
        assert_eq!(style.get(PaddingBottom), Length::Pt(45.0));

        let custom_padding = Padding::new().left(100.0).right(200.0);
        let style1 = Style::new().apply_padding(custom_padding);
        assert_eq!(style1.get(PaddingLeft), Length::Pt(100.0));
        assert_eq!(style1.get(PaddingRight), Length::Pt(200.0));
    }

    #[test]
    fn context_value_resolves_at_property_read() {
        let style = Style::new()
            .set(TextColor, Some(css::RED))
            .with::<TextColor>(|s, t| s.set_context(Background, t.map(|tc| tc.map(Brush::Solid))));
        assert_eq!(style.get(Background), Some(Brush::Solid(css::RED)));
    }
}
